### ISSUE TITLE
Request: clarify the `bitcoin-addr` vs. `bitcoin-key` separation

### ISSUE THREAD

**Issue by RecRanger** [klebs6/bitcoin-rs#4]
What's the difference between `bitcoin-addr` vs. `bitcoin-key`? It seems like `-key` is the actual key/address part of the bitcoin ecosystem, while `bitcoin-addr` seems strongly-linked to network addresses? 

`bitcoin-addr` doesn't seem to really offer any value. What's the point of it?

**Comment by klebs6** [comment]
the difference is that bitcoin-addr is part of the network stack whereas bitcoin-key is the data layout for the private keys.

the two abstractions serve different roles in the overall system.  for an example of how bitcoin-addr can be used, see `bitcoin-addrman`

**Comment by RecRanger** [comment]
Perhaps a better explanation should be added to the bitcoin-addr README then.

It could be as simple as something like:

> `bitcoin-addr` is the part of the network stack of this project, and is to be used for peer-to-peer (P2P) communciation between core nodes. For bitcoin address/key management, see the `bitcoin-key` library.

**Comment by klebs6** [comment]
Brilliant -- let's add it. I will create the modification.
see commit 1e8123c

**Comment by RecRanger** [comment]
Nice. That diff online is very tough to decipher, but I think it's a good change!

**Comment by klebs6** [comment]
The diff is noticing that I relaxed the line length constraint within my text editor. 

(probably better to make that change in a separate commit, but this is what happened)

Basically, the change is here:


<img width="1055" alt="Screenshot 2024-05-22 at 6 15 43 PM" src="https://github.com/klebs6/bitcoin-rs/assets/92199902/5adc09d5-b6ac-489d-a7a2-459bd675e55f">

**Comment by klebs6** [comment]
While we are on the subject of README improvements: I have been considering the possibility of recreating each of the crate README files.

I am aware that in the future it will be better for each of these files to be more concise and helpful.

For now, it does not feel like it is on the critical path. I am bottle-necked with other work which will hopefully incidentally benefit this project, too.

When I initially generated these README files, I used the gpt3.5 model available at the time to publicly probe both the crate interface as well as my understanding at the time of the generation.  

During the generation, I tried to ask the first questions which came to mind about each crate's contents from the perspective of somebody unfamiliar with bitcoin.

I felt it was useful to maximally document everything I could about what I knew about each crate so that others could accurately gauge the level of work which had been done as well as understand the scope of the remaining work. 

`better knowledge` + `more accurate ai models to converse with` = `better readme files`

The inputs to this equation have dramatically improved since the time of the README file authorship.  

Hopefully, the process of updating this information will soon be automated.  When I come back to it, automating the README generation is something I will be considering.

It may be worthwhile for me to create an additional issue discussing this possibility.

What do you think? Do you have any additional feedback?

**Comment by RecRanger** [comment]
It makes sense they were AI-generated; it seemed to jump back and forth in its explanation of what type of address it was talking about (IP address vs. bitcoin address), which fueled my confusion.

These READMEs should be much less verbose overall. They contain too much filler material in general. Giving the LLM a length limit would be valuable. 

All that said, I'm not sure how much it matters until the actual code is in a more usable state. The only important piece of information is really just that "this refactor is a work-in-progress."

**Comment by klebs6** [comment]
Agreed on all points. The jump in information density between model version 3.5 and 4 is notable.  Now being acclimated to 4, we need the information density in the old output provided by 3.5 to be higher.  I remember feeling that the output provided by model 3.5 was much better than what we had before (which was nothing). At the time, though, we did not have an efficient way to compress further without making manual temporary edits.

IMO this will be an iterative phenomenon as the models improve and the workflows stabilize.

It seems to me that the bottleneck is the information density provided by the AI models as well as the ability for the AI to operate on full crates with proper context. 

That said, once we build *that* we also get *this* project and a whole lot of new things become possible.

Thank you for the feedback  👍🌿
