### ISSUE TITLE
Future of the `bitcoin-primitives` crate

### ISSUE THREAD

**Issue by tcharding** [klebs6/bitcoin-rs#6]
Hi klebs6, thanks a bunch for adding me and apoelstra as owners of the `bitcoin-primitives` crate. I wanted to open an issue just to make sure we are all on the same page.

Was it your intention to keep any of the current released code in this crate? Or are you ok for us to totally clobber the current crate and release the `primitives` crate being created in [`rust-bitcoin`](https://github.com/rust-bitcoin/rust-bitcoin/pull/2883)?

Thanks man, appreciate you working with us.

**Comment by tcharding** [comment]
CC @klebs6 @apoelstra (so the mentions are not in the issue description causing spam).

**Comment by tcharding** [comment]
Oh I hadn't read my notifications when I posted this. You already answered here: https://github.com/rust-bitcoin/rust-bitcoin/pull/2756#issuecomment-2181864593

Thanks man!

**Comment by klebs6** [comment]
happy to help! yes, to confirm: you can clobber it! As you read, I already refactored everything out.  There exists a small number of new, more granular crates which now hold the contents of what had been in `bitcoin-primitives`.  The rest of the workspace now properly links with these new crates instead of the bitcoin_primitives crate.

I plan to bump the version of the whole workspace and release once *this* gets merged and released: https://github.com/jmagnuson/libevent-rs/pull/23

**Comment by klebs6** [comment]
we now have something like:
`bitcoin-u256`
`bitcoin-u160`
`bitcoin-bitstream`
`bitcoin-blob`
`bitcoin-bigint`
`bitcoin-autofile`
`bitcoin-bufferedfile`
`bitcoin-vectorstream`
